<?php

$customers = Mage::getResourceModel('customer/customer_collection')->addNameToSelect();

?>

<div class="page-title">
    <h1><?php echo $this->__('Track Customers') ?></h1>
</div>

<?php echo $this->getMessagesBlock()->toHtml() ?>

<div>
<form action="<?php echo $this->getUrl('track/index/index') ?>" method="post" id="form-validate">
    <table width="100%">
    <thead>
        <th>Tracked</th>
        <th>Name</th>
        <th>Email</th>
    </thead>
        <?php
        foreach ($customers as $customer):
            $customerObj = Mage::getModel('customer/customer'); //Bad news to load this in a loop, but load() would not work otherwise
            $customerId = (int)$customer->getID();
            $isTracked = $customerObj->load($customerId)->getIsTracked();
        ?>
            <tr>
                <td><input type="checkbox" name="trackCheck[]" value=<?php echo $customerId ?> <?php if($isTracked):?>checked<?php endif; ?> ></td>
                <td><?php echo $customer->getData('name'); ?></td>
                <td><?php echo $customer->getEmail(); ?></td>
            </tr>
        <?php
        endforeach;
        ?>
    </table>
    <button type="submit" title="<?php echo $this->__('Save Tracked Customers') ?>" class="button" name="track" value="track"><span><span><?php echo $this->__('Save Tracked Customers') ?></span></span></button>
</form>
</div>