
<div class="page-title">
    <h1><?php echo $this->__('Reset All Passwords') ?></h1>
</div>

<div>
	<form action="<?php echo $this->getUrl('nuke/passwords/index/') ?>" method="post" id="form-validate">
		<p>Enter Password to give all users:</p>
		<input type="text" name="newPassword" />
	    <button type="submit" title="<?php echo $this->__('Reset Passwords') ?>" class="button"><span><span><?php echo $this->__('Reset Passwords') ?></span></span></button>
    </form>
</div>