
<div class="page-title">
    <h1><?php echo $this->__('Disable All Products') ?></h1>
</div>

<div>
	<form action="<?php echo $this->getUrl('nuke/products/index/') ?>" method="post" id="form-validate">
		<p>Disable All Products by clicking below. I can't help you on the other side</p>
	    <button type="submit" title="<?php echo $this->__('Disable All Products') ?>" class="button"><span><span><?php echo $this->__('Disable All Products') ?></span></span></button>
</div>